### ISSUE TITLE
[feature] take a default git branch for revision argument

### ISSUE THREAD

**Issue by holamgadol** [foliant-docs/foliantcontrib.history#1]
`revision` argument is [defined](https://github.com/foliant-docs/foliantcontrib.history/blob/a31f69849505ea88ac1b12c4935a8c188a48dbe8/foliant/preprocessors/history.py#L22) as _master_ by default.

- Change the `revision` argument to be defined as _default branch_ in git terms.
- Check your changes in foliant-docs [history if releases](https://foliant-docs.github.io/docs/releases/)
  - the [usage](https://github.com/foliant-docs/docs/blob/94e70e4adb1111ef02707736e1057e57b5b6f1ab/foliant.yml#L109) of history in folaint-docs
- It should work for github repos necessarily

Optional:
 - make it work for gitlab

**Comment by TOsmanov** [comment]
@holamgadol , I found that if leave `revision` empty, the history block is generated correctly, apparently the absence of a branch is still the default branch?

```py
        'revision': '',
```

**Comment by holamgadol** [comment]
@TOsmanov  You can check your assumption on this project: https://github.com/foliant-docs/foliantcontrib.checksources
If an empty `revision` pulls the `main` branch here, you are right

**Comment by TOsmanov** [comment]
@holamgadol `foliant make site` will not output errors if uncomment line `https://github.com/foliant-docs/foliantcontrib.check sources.git` in `repos.yml` ,  but there is no information about the `foliantcontrib.checksources` on the History of Releases page. What should be on the History of Releases page about `foliantcontrib.check sources`, something like: "checksources 1.0.0 Initial release"?

**Comment by holamgadol** [comment]
@TOsmanov my bad, there was no changelog in checksources. Just added it. Check it out now, please.

**Comment by TOsmanov** [comment]
@holamgadol now everything is displayed correctly

![image](https://user-images.githubusercontent.com/54434686/187473056-875b97b4-901c-4730-aff2-40f874d6a58d.png)
